import __main__ as main
import os

def read_file(fn):
    with open(fn, "r") as f:
        return f.read()

def build_header():
    return """###
### This file was generated by %s for the ZCash build system.
### Do not edit.
###
### When updating this dependency, re-run this script in the dependency's source
### directory and replace this file with the BUILD.bazel file that the script
### generates.
###

""" % os.path.basename(main.__file__)
